apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conscoord-api-ingress
  namespace: kgb-conscoord
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-conscoord-production
spec:
  tls:
  - hosts:
    - conscoord.duckdns.org
    secretName: conscoord-production
  rules:
  - host: conscoord.duckdns.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: conscoord-api-service
            port:
              number: 8080
              