services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=conscoord.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      # - STAGING=false
    volumes:
      - </path/to/appdata/config>:/config
    ports:
      - 443:443
    restart: unless-stopped