name: Build and deploy on kubernetes
on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, conscoord-api]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t garioncox/conscoord-api:${{ github.run_number }} \
            -t garioncox/conscoord-api:latest \
          .

      - name: Push image
        run: |
          docker push garioncox/conscoord-api --all-tags

      - name: Deploy to Kubernetes
        run: |
          export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin

          export IMAGE_TAG=${{ github.run_number }}
          export DB=${{ secrets.DB }}
          export SMTP_SENDERNAME=${{ secrets.SMTP_SENDERNAME }}
          export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          export EMAIL_ENABLED=${{ env.EMAIL_ENABLED }}

          for file in kube/*; do
              echo "Applying $file"
              cat "$file" | envsubst | kubectl apply -f -;
          done
